kind: PersistentVolume
apiVersion: v1
metadata:
 name: pv0001
 labels:
  type: local
spec:
 storageClassName: manual
 capacity:
  storage: 10Gi
 accessModes:
   - ReadWriteOnce
 hostPath:
  path: "/tmp/data01"
